package com.dream.socket.protobuf;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

public final class Protobuf {
    private Protobuf() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface MessageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Message)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         *消息ID
         * </pre>
         *
         * <code>string id = 1;</code>
         */
        String getId();
        /**
         * <pre>
         *消息ID
         * </pre>
         *
         * <code>string id = 1;</code>
         */
        com.google.protobuf.ByteString
        getIdBytes();

        /**
         * <pre>
         *消息类型
         * </pre>
         *
         * <code>sint32 type = 2;</code>
         */
        int getType();

        /**
         * <pre>
         *发送者
         * </pre>
         *
         * <code>sint64 sender = 3;</code>
         */
        long getSender();

        /**
         * <pre>
         *内容,更具类型转换成相应类型
         * </pre>
         *
         * <code>bytes content = 4;</code>
         */
        com.google.protobuf.ByteString getContent();
    }
    /**
     * <pre>
     *接收消息
     * </pre>
     *
     * Protobuf type {@code Message}
     */
    public  static final class Message extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Message)
            MessageOrBuilder {
        // Use Message.newBuilder() to construct.
        private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private Message() {
            id_ = "";
            type_ = 0;
            sender_ = 0L;
            content_ = com.google.protobuf.ByteString.EMPTY;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }
        private Message(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            String s = input.readStringRequireUtf8();

                            id_ = s;
                            break;
                        }
                        case 16: {

                            type_ = input.readSInt32();
                            break;
                        }
                        case 24: {

                            sender_ = input.readSInt64();
                            break;
                        }
                        case 34: {

                            content_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Protobuf.internal_static_Message_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Protobuf.internal_static_Message_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Message.class, Builder.class);
        }

        public static final int ID_FIELD_NUMBER = 1;
        private volatile Object id_;
        /**
         * <pre>
         *消息ID
         * </pre>
         *
         * <code>string id = 1;</code>
         */
        public String getId() {
            Object ref = id_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                id_ = s;
                return s;
            }
        }
        /**
         * <pre>
         *消息ID
         * </pre>
         *
         * <code>string id = 1;</code>
         */
        public com.google.protobuf.ByteString
        getIdBytes() {
            Object ref = id_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                id_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int TYPE_FIELD_NUMBER = 2;
        private int type_;
        /**
         * <pre>
         *消息类型
         * </pre>
         *
         * <code>sint32 type = 2;</code>
         */
        public int getType() {
            return type_;
        }

        public static final int SENDER_FIELD_NUMBER = 3;
        private long sender_;
        /**
         * <pre>
         *发送者
         * </pre>
         *
         * <code>sint64 sender = 3;</code>
         */
        public long getSender() {
            return sender_;
        }

        public static final int CONTENT_FIELD_NUMBER = 4;
        private com.google.protobuf.ByteString content_;
        /**
         * <pre>
         *内容,更具类型转换成相应类型
         * </pre>
         *
         * <code>bytes content = 4;</code>
         */
        public com.google.protobuf.ByteString getContent() {
            return content_;
        }

        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getIdBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
            }
            if (type_ != 0) {
                output.writeSInt32(2, type_);
            }
            if (sender_ != 0L) {
                output.writeSInt64(3, sender_);
            }
            if (!content_.isEmpty()) {
                output.writeBytes(4, content_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getIdBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
            }
            if (type_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeSInt32Size(2, type_);
            }
            if (sender_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeSInt64Size(3, sender_);
            }
            if (!content_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(4, content_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;
        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Message)) {
                return super.equals(obj);
            }
            Message other = (Message) obj;

            boolean result = true;
            result = result && getId()
                    .equals(other.getId());
            result = result && (getType()
                    == other.getType());
            result = result && (getSender()
                    == other.getSender());
            result = result && getContent()
                    .equals(other.getContent());
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + ID_FIELD_NUMBER;
            hash = (53 * hash) + getId().hashCode();
            hash = (37 * hash) + TYPE_FIELD_NUMBER;
            hash = (53 * hash) + getType();
            hash = (37 * hash) + SENDER_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getSender());
            hash = (37 * hash) + CONTENT_FIELD_NUMBER;
            hash = (53 * hash) + getContent().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static Message parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Message parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Message parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Message parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Message parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Message parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Message parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Message parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static Message parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static Message parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static Message parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Message parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(Message prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * <pre>
         *接收消息
         * </pre>
         *
         * Protobuf type {@code Message}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Message)
                MessageOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Protobuf.internal_static_Message_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Protobuf.internal_static_Message_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Message.class, Builder.class);
            }

            // Construct using Protobuf.Message.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            public Builder clear() {
                super.clear();
                id_ = "";

                type_ = 0;

                sender_ = 0L;

                content_ = com.google.protobuf.ByteString.EMPTY;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Protobuf.internal_static_Message_descriptor;
            }

            public Message getDefaultInstanceForType() {
                return Message.getDefaultInstance();
            }

            public Message build() {
                Message result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public Message buildPartial() {
                Message result = new Message(this);
                result.id_ = id_;
                result.type_ = type_;
                result.sender_ = sender_;
                result.content_ = content_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Message) {
                    return mergeFrom((Message)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Message other) {
                if (other == Message.getDefaultInstance()) return this;
                if (!other.getId().isEmpty()) {
                    id_ = other.id_;
                    onChanged();
                }
                if (other.getType() != 0) {
                    setType(other.getType());
                }
                if (other.getSender() != 0L) {
                    setSender(other.getSender());
                }
                if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
                    setContent(other.getContent());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Message parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Message) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private Object id_ = "";
            /**
             * <pre>
             *消息ID
             * </pre>
             *
             * <code>string id = 1;</code>
             */
            public String getId() {
                Object ref = id_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    id_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }
            /**
             * <pre>
             *消息ID
             * </pre>
             *
             * <code>string id = 1;</code>
             */
            public com.google.protobuf.ByteString
            getIdBytes() {
                Object ref = id_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    id_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <pre>
             *消息ID
             * </pre>
             *
             * <code>string id = 1;</code>
             */
            public Builder setId(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                id_ = value;
                onChanged();
                return this;
            }
            /**
             * <pre>
             *消息ID
             * </pre>
             *
             * <code>string id = 1;</code>
             */
            public Builder clearId() {

                id_ = getDefaultInstance().getId();
                onChanged();
                return this;
            }
            /**
             * <pre>
             *消息ID
             * </pre>
             *
             * <code>string id = 1;</code>
             */
            public Builder setIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                id_ = value;
                onChanged();
                return this;
            }

            private int type_ ;
            /**
             * <pre>
             *消息类型
             * </pre>
             *
             * <code>sint32 type = 2;</code>
             */
            public int getType() {
                return type_;
            }
            /**
             * <pre>
             *消息类型
             * </pre>
             *
             * <code>sint32 type = 2;</code>
             */
            public Builder setType(int value) {

                type_ = value;
                onChanged();
                return this;
            }
            /**
             * <pre>
             *消息类型
             * </pre>
             *
             * <code>sint32 type = 2;</code>
             */
            public Builder clearType() {

                type_ = 0;
                onChanged();
                return this;
            }

            private long sender_ ;
            /**
             * <pre>
             *发送者
             * </pre>
             *
             * <code>sint64 sender = 3;</code>
             */
            public long getSender() {
                return sender_;
            }
            /**
             * <pre>
             *发送者
             * </pre>
             *
             * <code>sint64 sender = 3;</code>
             */
            public Builder setSender(long value) {

                sender_ = value;
                onChanged();
                return this;
            }
            /**
             * <pre>
             *发送者
             * </pre>
             *
             * <code>sint64 sender = 3;</code>
             */
            public Builder clearSender() {

                sender_ = 0L;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
            /**
             * <pre>
             *内容,更具类型转换成相应类型
             * </pre>
             *
             * <code>bytes content = 4;</code>
             */
            public com.google.protobuf.ByteString getContent() {
                return content_;
            }
            /**
             * <pre>
             *内容,更具类型转换成相应类型
             * </pre>
             *
             * <code>bytes content = 4;</code>
             */
            public Builder setContent(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                content_ = value;
                onChanged();
                return this;
            }
            /**
             * <pre>
             *内容,更具类型转换成相应类型
             * </pre>
             *
             * <code>bytes content = 4;</code>
             */
            public Builder clearContent() {

                content_ = getDefaultInstance().getContent();
                onChanged();
                return this;
            }
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:Message)
        }

        // @@protoc_insertion_point(class_scope:Message)
        private static final Message DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new Message();
        }

        public static Message getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Message>
                PARSER = new com.google.protobuf.AbstractParser<Message>() {
            public Message parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Message(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Message> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<Message> getParserForType() {
            return PARSER;
        }

        public Message getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface ConversationOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Conversation)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         *接收者
         * </pre>
         *
         * <code>sint64 receiver = 1;</code>
         */
        long getReceiver();

        /**
         * <pre>
         *聊天消息类型
         * </pre>
         *
         * <code>sint32 type = 2;</code>
         */
        int getType();

        /**
         * <pre>
         *文本内容
         * </pre>
         *
         * <code>string text = 3;</code>
         */
        String getText();
        /**
         * <pre>
         *文本内容
         * </pre>
         *
         * <code>string text = 3;</code>
         */
        com.google.protobuf.ByteString
        getTextBytes();
    }
    /**
     * Protobuf type {@code Conversation}
     */
    public  static final class Conversation extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Conversation)
            ConversationOrBuilder {
        // Use Conversation.newBuilder() to construct.
        private Conversation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private Conversation() {
            receiver_ = 0L;
            type_ = 0;
            text_ = "";
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }
        private Conversation(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {

                            receiver_ = input.readSInt64();
                            break;
                        }
                        case 16: {

                            type_ = input.readSInt32();
                            break;
                        }
                        case 26: {
                            String s = input.readStringRequireUtf8();

                            text_ = s;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Protobuf.internal_static_Conversation_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Protobuf.internal_static_Conversation_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Conversation.class, Builder.class);
        }

        public static final int RECEIVER_FIELD_NUMBER = 1;
        private long receiver_;
        /**
         * <pre>
         *接收者
         * </pre>
         *
         * <code>sint64 receiver = 1;</code>
         */
        public long getReceiver() {
            return receiver_;
        }

        public static final int TYPE_FIELD_NUMBER = 2;
        private int type_;
        /**
         * <pre>
         *聊天消息类型
         * </pre>
         *
         * <code>sint32 type = 2;</code>
         */
        public int getType() {
            return type_;
        }

        public static final int TEXT_FIELD_NUMBER = 3;
        private volatile Object text_;
        /**
         * <pre>
         *文本内容
         * </pre>
         *
         * <code>string text = 3;</code>
         */
        public String getText() {
            Object ref = text_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                text_ = s;
                return s;
            }
        }
        /**
         * <pre>
         *文本内容
         * </pre>
         *
         * <code>string text = 3;</code>
         */
        public com.google.protobuf.ByteString
        getTextBytes() {
            Object ref = text_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                text_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (receiver_ != 0L) {
                output.writeSInt64(1, receiver_);
            }
            if (type_ != 0) {
                output.writeSInt32(2, type_);
            }
            if (!getTextBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, text_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (receiver_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeSInt64Size(1, receiver_);
            }
            if (type_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeSInt32Size(2, type_);
            }
            if (!getTextBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, text_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;
        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Conversation)) {
                return super.equals(obj);
            }
            Conversation other = (Conversation) obj;

            boolean result = true;
            result = result && (getReceiver()
                    == other.getReceiver());
            result = result && (getType()
                    == other.getType());
            result = result && getText()
                    .equals(other.getText());
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + RECEIVER_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getReceiver());
            hash = (37 * hash) + TYPE_FIELD_NUMBER;
            hash = (53 * hash) + getType();
            hash = (37 * hash) + TEXT_FIELD_NUMBER;
            hash = (53 * hash) + getText().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static Conversation parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Conversation parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Conversation parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Conversation parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Conversation parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Conversation parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Conversation parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Conversation parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static Conversation parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static Conversation parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static Conversation parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Conversation parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(Conversation prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code Conversation}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Conversation)
                ConversationOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Protobuf.internal_static_Conversation_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Protobuf.internal_static_Conversation_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Conversation.class, Builder.class);
            }

            // Construct using Protobuf.Conversation.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            public Builder clear() {
                super.clear();
                receiver_ = 0L;

                type_ = 0;

                text_ = "";

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Protobuf.internal_static_Conversation_descriptor;
            }

            public Conversation getDefaultInstanceForType() {
                return Conversation.getDefaultInstance();
            }

            public Conversation build() {
                Conversation result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public Conversation buildPartial() {
                Conversation result = new Conversation(this);
                result.receiver_ = receiver_;
                result.type_ = type_;
                result.text_ = text_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Conversation) {
                    return mergeFrom((Conversation)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Conversation other) {
                if (other == Conversation.getDefaultInstance()) return this;
                if (other.getReceiver() != 0L) {
                    setReceiver(other.getReceiver());
                }
                if (other.getType() != 0) {
                    setType(other.getType());
                }
                if (!other.getText().isEmpty()) {
                    text_ = other.text_;
                    onChanged();
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Conversation parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Conversation) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private long receiver_ ;
            /**
             * <pre>
             *接收者
             * </pre>
             *
             * <code>sint64 receiver = 1;</code>
             */
            public long getReceiver() {
                return receiver_;
            }
            /**
             * <pre>
             *接收者
             * </pre>
             *
             * <code>sint64 receiver = 1;</code>
             */
            public Builder setReceiver(long value) {

                receiver_ = value;
                onChanged();
                return this;
            }
            /**
             * <pre>
             *接收者
             * </pre>
             *
             * <code>sint64 receiver = 1;</code>
             */
            public Builder clearReceiver() {

                receiver_ = 0L;
                onChanged();
                return this;
            }

            private int type_ ;
            /**
             * <pre>
             *聊天消息类型
             * </pre>
             *
             * <code>sint32 type = 2;</code>
             */
            public int getType() {
                return type_;
            }
            /**
             * <pre>
             *聊天消息类型
             * </pre>
             *
             * <code>sint32 type = 2;</code>
             */
            public Builder setType(int value) {

                type_ = value;
                onChanged();
                return this;
            }
            /**
             * <pre>
             *聊天消息类型
             * </pre>
             *
             * <code>sint32 type = 2;</code>
             */
            public Builder clearType() {

                type_ = 0;
                onChanged();
                return this;
            }

            private Object text_ = "";
            /**
             * <pre>
             *文本内容
             * </pre>
             *
             * <code>string text = 3;</code>
             */
            public String getText() {
                Object ref = text_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    text_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }
            /**
             * <pre>
             *文本内容
             * </pre>
             *
             * <code>string text = 3;</code>
             */
            public com.google.protobuf.ByteString
            getTextBytes() {
                Object ref = text_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    text_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <pre>
             *文本内容
             * </pre>
             *
             * <code>string text = 3;</code>
             */
            public Builder setText(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                text_ = value;
                onChanged();
                return this;
            }
            /**
             * <pre>
             *文本内容
             * </pre>
             *
             * <code>string text = 3;</code>
             */
            public Builder clearText() {

                text_ = getDefaultInstance().getText();
                onChanged();
                return this;
            }
            /**
             * <pre>
             *文本内容
             * </pre>
             *
             * <code>string text = 3;</code>
             */
            public Builder setTextBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                text_ = value;
                onChanged();
                return this;
            }
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:Conversation)
        }

        // @@protoc_insertion_point(class_scope:Conversation)
        private static final Conversation DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new Conversation();
        }

        public static Conversation getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Conversation>
                PARSER = new com.google.protobuf.AbstractParser<Conversation>() {
            public Conversation parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Conversation(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Conversation> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<Conversation> getParserForType() {
            return PARSER;
        }

        public Conversation getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface TextOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Text)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string text = 1;</code>
         */
        String getText();
        /**
         * <code>string text = 1;</code>
         */
        com.google.protobuf.ByteString
        getTextBytes();
    }
    /**
     * Protobuf type {@code Text}
     */
    public  static final class Text extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Text)
            TextOrBuilder {
        // Use Text.newBuilder() to construct.
        private Text(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private Text() {
            text_ = "";
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }
        private Text(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            String s = input.readStringRequireUtf8();

                            text_ = s;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Protobuf.internal_static_Text_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Protobuf.internal_static_Text_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Text.class, Builder.class);
        }

        public static final int TEXT_FIELD_NUMBER = 1;
        private volatile Object text_;
        /**
         * <code>string text = 1;</code>
         */
        public String getText() {
            Object ref = text_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                text_ = s;
                return s;
            }
        }
        /**
         * <code>string text = 1;</code>
         */
        public com.google.protobuf.ByteString
        getTextBytes() {
            Object ref = text_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                text_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getTextBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, text_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getTextBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, text_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;
        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Text)) {
                return super.equals(obj);
            }
            Text other = (Text) obj;

            boolean result = true;
            result = result && getText()
                    .equals(other.getText());
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + TEXT_FIELD_NUMBER;
            hash = (53 * hash) + getText().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static Text parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Text parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Text parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Text parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Text parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Text parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Text parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Text parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static Text parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static Text parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static Text parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Text parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(Text prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code Text}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Text)
                TextOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Protobuf.internal_static_Text_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Protobuf.internal_static_Text_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Text.class, Builder.class);
            }

            // Construct using Protobuf.Text.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            public Builder clear() {
                super.clear();
                text_ = "";

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Protobuf.internal_static_Text_descriptor;
            }

            public Text getDefaultInstanceForType() {
                return Text.getDefaultInstance();
            }

            public Text build() {
                Text result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public Text buildPartial() {
                Text result = new Text(this);
                result.text_ = text_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Text) {
                    return mergeFrom((Text)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Text other) {
                if (other == Text.getDefaultInstance()) return this;
                if (!other.getText().isEmpty()) {
                    text_ = other.text_;
                    onChanged();
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Text parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Text) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private Object text_ = "";
            /**
             * <code>string text = 1;</code>
             */
            public String getText() {
                Object ref = text_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    text_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }
            /**
             * <code>string text = 1;</code>
             */
            public com.google.protobuf.ByteString
            getTextBytes() {
                Object ref = text_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    text_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string text = 1;</code>
             */
            public Builder setText(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                text_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string text = 1;</code>
             */
            public Builder clearText() {

                text_ = getDefaultInstance().getText();
                onChanged();
                return this;
            }
            /**
             * <code>string text = 1;</code>
             */
            public Builder setTextBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                text_ = value;
                onChanged();
                return this;
            }
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:Text)
        }

        // @@protoc_insertion_point(class_scope:Text)
        private static final Text DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new Text();
        }

        public static Text getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Text>
                PARSER = new com.google.protobuf.AbstractParser<Text>() {
            public Text parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Text(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Text> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<Text> getParserForType() {
            return PARSER;
        }

        public Text getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Message_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Message_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Conversation_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Conversation_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Text_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Text_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        String[] descriptorData = {
                "\n\016protobuf.proto\"D\n\007Message\022\n\n\002id\030\001 \001(\t\022" +
                        "\014\n\004type\030\002 \001(\021\022\016\n\006sender\030\003 \001(\022\022\017\n\007content" +
                        "\030\004 \001(\014\"<\n\014Conversation\022\020\n\010receiver\030\001 \001(\022" +
                        "\022\014\n\004type\030\002 \001(\021\022\014\n\004text\030\003 \001(\t\"\024\n\004Text\022\014\n\004" +
                        "text\030\001 \001(\tB\nB\010Protobufb\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
        internal_static_Message_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_Message_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Message_descriptor,
                new String[] { "Id", "Type", "Sender", "Content", });
        internal_static_Conversation_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_Conversation_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Conversation_descriptor,
                new String[] { "Receiver", "Type", "Text", });
        internal_static_Text_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_Text_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Text_descriptor,
                new String[] { "Text", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
